# Generated by Django 4.0.3 on 2022-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
