# Generated by Django 4.0.3 on 2022-03-23 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_time_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='available_time_to',
        ),
        migrations.CreateModel(
            name='WeekDayAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
