# Generated by Django 4.0.3 on 2022-03-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ratingmodel_myrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
