# Generated by Django 4.0.3 on 2022-03-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_ratingmodel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrate',
            name='by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_rates', to=settings.AUTH_USER_MODEL),
        ),
    ]
