# Generated by Django 4.0.3 on 2022-03-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_myrate_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrate',
            name='of_rating',
        ),
    ]
