# Generated by Django 4.0.3 on 2022-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_myrate_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
